export const hotelsData = [
  {
    HotelName: "Luxury Hotel",
    type: "Hotel",
    country: "United States",
    city: "Miami",
    address: "123 Ocean Drive",
    distance: "2 miles from downtown",
    photos: [
      "https://t3.ftcdn.net/jpg/00/29/13/38/360_F_29133877_bfA2n7cWV53fto2BomyZ6pyRujJTBwjd.jpg",
      "https://hips.hearstapps.com/hmg-prod/images/main-pool-sunrise-650dbf345ec36.jpg?crop=1.00xw:0.669xh;0,0.222xh&resize=1200:*",
      "https://media.istockphoto.com/id/119926339/photo/resort-swimming-pool.jpg?s=612x612&w=0&k=20&c=9QtwJC2boq3GFHaeDsKytF4-CavYKQuy1jBD2IRfYKc=",
    ],
    title: "Experience luxury at its finest",
    description:
      "Indulge in world-class amenities and breathtaking views at our luxurious resort.",
    rating: 4.8,
    rooms: [
      "6672f1d9ed6828ee3339db81",
      "6672f1d9ed6828ee3339dbb4",
      "6672f1d9ed6828ee3339dbe7",
    ],
    reviews: [],
    cheapestPrice: 300,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Cozy Inn",
    type: "Hotel",
    country: "France",
    city: "Paris",
    address: "456 Rue de la Paix",
    distance: "1 mile from Eiffel Tower",
    photos: [
      "https://gos3.ibcdn.com/965ec8c40dae11e8976f0a9df65c8753.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIvNV03mEEmsdj1mqqswjmBgapGx9_gCvoEyfhRZcenrFSn-ZHKPUqqlkNJePX4ict6tM&usqp=CAU",
    ],
    title: "Experience Parisian charm",
    description:
      "Enjoy a comfortable stay in the heart of Paris with our cozy rooms and warm hospitality.",
    rating: 4.2,
    rooms: [],
    reviews: [],
    cheapestPrice: 150,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Tropical Paradise Hotel",
    type: "Hotel",
    country: "Thailand",
    city: "Phuket",
    address: "789 Beach Road",
    distance: "On the beachfront",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgctGze-jMMOm05h__UbxntR11VPBcsyLG4A&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVDHmODLqoApedQNNs0JIyrae9cgyL76tW-w&s",
    ],
    title: "Escape to paradise",
    description:
      "Immerse yourself in the beauty of Phuket with our stunning beachfront resort and world-class amenities.",
    rating: 4.6,
    rooms: [],
    reviews: [],
    cheapestPrice: 250,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "City View Hotel",
    type: "Hotel",
    country: "United States",
    city: "New York",
    address: "789 Broadway",
    distance: "1 mile from Times Square",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTajMhZekjJTl2Nfdk4qRpkKVaz86a0Btxeig&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiQ69Phf_fcWARHT-qounTLJkY-McRT7GPLw&s",
    ],
    title: "Enjoy the stunning city views",
    description:
      "Stay in the heart of New York City and experience breathtaking views of the city skyline.",
    rating: 4.5,
    rooms: [],
    reviews: [],
    cheapestPrice: 200,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Mountain Retreat",
    type: "Hotel",
    country: "Switzerland",
    city: "Zermatt",
    address: "456 Alpine Street",
    distance: "In the Swiss Alps",
    photos: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/251981326.jpg?k=f9569bee65451ee5a28b114f164ec2077a34421c25485a44d2677b798faa47ec&o=&hp=1",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/251981356.jpg?k=f4d8779fac895b28a6730b012e8fbfc1c0ceb90ef26e5b389e2ae81988eb7296&o=&hp=1",
    ],
    title: "Escape to the serene mountains",
    description:
      "Experience tranquility and natural beauty in our cozy mountain retreat in Zermatt.",
    rating: 4.7,
    rooms: [],
    reviews: [],
    cheapestPrice: 350,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Beachfront Hotel",
    type: "Hotel",
    country: "Mexico",
    city: "Cancun",
    address: "123 Beach Boulevard",
    distance: "On the beachfront",
    photos: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/337400838.jpg?k=00ea86407968f76530b9193a27e00173282b0d3c9e3f12488e45908f1be7325f&o=&hp=1",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpwizPC2fkAd0aX7fVB9oB0pyJ0HSpkGiy8Q&s",
    ],
    title: "Unwind in paradise",
    description:
      "Relax and rejuvenate at our beachfront resort in Cancun with pristine white sand and crystal-clear waters.",
    rating: 4.4,
    rooms: [],
    reviews: [],
    cheapestPrice: 280,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Luxor Palace",
    type: "Hotel",
    country: "Egypt",
    city: "Luxor",
    address: "789 Nile Street",
    distance: "Near Luxor Temple",
    photos: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/496537295.jpg?k=10e8ff9fb3af3ad10036bcdd9fe37ad72319443fed88e66b98e7e4f239bc7b08&o=&hp=1",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf-IbTnRT3t9a5be20lEhmqeppWz9GGWDz4lgi-2uqurlVn0oOdiCD3xQbMz7CS8-Rcnw&usqp=CAU",
    ],
    title: "Discover ancient wonders",
    description:
      "Immerse yourself in the rich history of Luxor while enjoying luxurious accommodations at our palace hotel.",
    rating: 4.7,
    rooms: [],
    reviews: [],
    cheapestPrice: 200,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Grand Canyon Lodge",
    type: "Hotel",
    country: "United States",
    city: "Arizona",
    address: "123 Canyon Road",
    distance: "Inside Grand Canyon National Park",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ15SZc_pRhQ-__mjAbNy3DH5A_w6QykRCnNA&s",
    ],
    title: "Experience nature's grandeur",
    description:
      "Stay in a lodge nestled within the breathtaking beauty of the Grand Canyon and enjoy stunning views.",
    rating: 4.9,
    rooms: [],
    reviews: [],
    cheapestPrice: 250,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "London Luxury Hotel",
    type: "Hotel",
    country: "United Kingdom",
    city: "London",
    address: "456 Park Lane",
    distance: "In the city center",
    photos: [
      "https://img1.10bestmedia.com/Images/Photos/312234/Ritz3_55_660x440.jpg",
    ],
    title: "Indulge in luxury",
    description:
      "Experience the epitome of luxury and sophistication at our prestigious hotel in the heart of London.",
    rating: 4.8,
    rooms: [],
    reviews: [],
    cheapestPrice: 350,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Barcelona Beach Hotel",
    type: "Hotel",
    country: "Spain",
    city: "Barcelona",
    address: "789 Beachfront Avenue",
    distance: "On the beachfront",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8kkN7XwdKe3tYzC3XD9frZ8cYd2HXaoM_w-Fo69MQpoC0DJR_ow64OZumjzDRzTjww80&usqp=CAU",
      "https://res.cloudinary.com/hello-tickets/image/upload/c_limit,f_auto,q_auto,w_768/v1658290389/post_images/barcelona-122/Night/41296729261_31c5aabc99_o_Cropped.jpg",
    ],
    title: "Relax by the Mediterranean",
    description:
      "Enjoy a beachfront getaway in Barcelona with stunning views of the Mediterranean Sea.",
    rating: 4.5,
    rooms: [],
    reviews: [],
    cheapestPrice: 280,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Venice Canalside Hotel",
    type: "Hotel",
    country: "Italy",
    city: "Venice",
    address: "123 Canalside Street",
    distance: "Near St. Mark's Square",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_haMSMMIxvz-BYSw0POdU6TutbegiTUoI7A&s",
    ],
    title: "Experience the charm of Venice",
    description:
      "Stay in a traditional hotel nestled along the picturesque canals of Venice and soak in the city's romantic atmosphere.",
    rating: 4.6,
    rooms: [],
    reviews: [],
    cheapestPrice: 240,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Riviera Maya Hotel",
    type: "Hotel",
    country: "Mexico",
    city: "Playa del Carmen",
    address: "123 Riviera Avenue",
    distance: "On the Riviera Maya",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvjD6aCYZatJiQkvExigUL1hUAqgh04WPkuQ&s",
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/cf/b0/80/secrets-maroma-beach.jpg?w=1200&h=-1&s=1",
    ],
    title: "Escape to paradise",
    description:
      "Relax and unwind at our luxurious resort on the beautiful Riviera Maya with pristine beaches and turquoise waters.",
    rating: 4.7,
    rooms: [],
    reviews: [],
    cheapestPrice: 320,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Tokyo Tower Hotel",
    type: "Hotel",
    country: "Japan",
    city: "Tokyo",
    address: "789 Tower Street",
    distance: "Near Tokyo Tower",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3vDyFVu2tGK23MdSZNuo3UCuOnI8kveB-Jw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYaGxLLmoeCDvO9dMmSC8NYat-Fq7bSxQeNA&s",
    ],
    title: "Stay with a view",
    description:
      "Experience the vibrant city of Tokyo from the heights of our hotel near the iconic Tokyo Tower.",
    rating: 4.7,
    rooms: [],
    reviews: [],
    cheapestPrice: 180,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Sydney Harbour Hotel",
    type: "Hotel",
    country: "Australia",
    city: "Sydney",
    address: "123 Harbour Street",
    distance: "Overlooking Sydney Harbour",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMzb3rQfwlyI9FQ7iH2BEo76Npn4sQaYqmNg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs4YXf6u7oO290JNTmiWmkb7iZQo2g75q6Lw&s",
    ],
    title: "Harbourfront luxury",
    description:
      "Enjoy stunning views of the Sydney Opera House and the Harbour Bridge from our elegant hotel.",
    rating: 4.9,
    rooms: [],
    reviews: [],
    cheapestPrice: 300,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "New York City Loft",
    type: "Hotel",
    country: "United States",
    city: "New York",
    address: "456 Loft Avenue",
    distance: "In the heart of Manhattan",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZD1T_tuy0DoMvj_mMihDdFF_xHJOg-bsI-g&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9OIkTypWNeXHtiE_saqUvgKeHodeHyoQe0Q&s",
    ],
    title: "Urban chic",
    description:
      "Experience the vibrant energy of New York City from our stylish loft hotel in the heart of Manhattan.",
    rating: 4.8,
    rooms: [],
    reviews: [],
    cheapestPrice: 400,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Parisian Elegance Hotel",
    type: "Hotel",
    country: "France",
    city: "Paris",
    address: "789 Champs-Élysées",
    distance: "On the famous avenue",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaVBrz5nTMlqJS645Eecft8kvKR7TsnZh2qgZkdqqsbX4OGnPPG3VJZYbKt_eR3QrmZc0&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXX3LP6O5cexLU-3I0zaWAZOfSmQ95clEFdA&s",
      "https://cdn.royist.com/wp-content/uploads/2020/03/shangri-la-paris5-scaled.jpg",
    ],
    title: "Experience Paris in style",
    description:
      "Immerse yourself in the romance and elegance of Paris at our luxurious hotel on the iconic Champs-Élysées.",
    rating: 4.7,
    rooms: [],
    reviews: [],
    cheapestPrice: 320,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Cape Town Beachfront Hotel",
    type: "Hotel",
    country: "South Africa",
    city: "Cape Town",
    address: "123 Beach Road",
    distance: "On the beachfront",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVW7xEC3LCHZ9oSLO-GKMkgm234RrKWCZxSw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMZ7OszWWMRO4gR_e_alzKablg_YKsbmRdJxDyzD55rPVoeFncgmXFaAxvkBITtDme5o4&usqp=CAU",
    ],
    title: "Spectacular coastal retreat",
    description:
      "Escape to our beachfront resort in Cape Town and enjoy breathtaking views of the ocean and Table Mountain.",
    rating: 4.6,
    rooms: [],
    reviews: [],
    cheapestPrice: 280,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Dubai Desert Oasis",
    type: "Hotel",
    country: "United Arab Emirates",
    city: "Dubai",
    address: "123 Oasis Road",
    distance: "In the desert",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD0D2tE74Yx5oTJCteLQLDQEGqrYP6dBOhAg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5IIza4aaOitxxS7-TC9BElLOSRZI6MTITFS0UnKQT1iK-hDCfy1HU9cMwe0iPC3kNsOA&usqp=CAU",
    ],
    title: "Luxury in the desert",
    description:
      "Experience the opulence and tranquility of our desert oasis hotel in the vibrant city of Dubai.",
    rating: 4.7,
    rooms: [],
    reviews: [],
    cheapestPrice: 350,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Rome Historic Palace",
    type: "Hotel",
    country: "Italy",
    city: "Rome",
    address: "789 Via del Colosseo",
    distance: "Next to the Colosseum",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRU3mUhhgd7KQXQEzYk2m5o_YYaRfWlB8T1SA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1FhJoyIrpt768QFM9VluV9vFuUMwSKshd4xse9CQZDuuIk9AMwKRCQNmglFHBfx2hCRE&usqp=CAU",
    ],
    title: "Step back in time",
    description:
      "Immerse yourself in the rich history of Rome at our historic palace hotel located next to the iconic Colosseum.",
    rating: 4.8,
    rooms: [],
    reviews: [],
    cheapestPrice: 280,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Bali Beach Hotel",
    type: "Hotel",
    country: "Indonesia",
    city: "Bali",
    address: "123 Beachfront Avenue",
    distance: "On the pristine beach",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlHF411zyG2ejz9yG9atm2PZKkE_CEo2X-hw&s",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/505136458.jpg?k=502f3b8b8967144a6077c4362d915d47af1fe46f5534cfdfc961d7f354a483c5&o=&hp=1",
    ],
    title: "Tropical paradise",
    description:
      "Escape to our beachfront resort in Bali and indulge in the beauty of the island's pristine beaches and lush landscapes.",
    rating: 4.9,
    rooms: [],
    reviews: [],
    cheapestPrice: 350,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "London Riverside Hotel",
    type: "Hotel",
    country: "United Kingdom",
    city: "London",
    address: "456 Thames Street",
    distance: "Along the River Thames",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsXs-9OOBuvPcX3qKH6QuE_FoizKB5UQaXwg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThtH_vuq2qH2RugZgpxa6Lj9QJgVXCaNPPffis5ZtV4OsBi8W7XRx3mIiG-rjx_uAJvC0&usqp=CAU",
    ],
    title: "Riverside luxury",
    description:
      "Experience the charm of London from our elegant hotel located along the iconic River Thames.",
    rating: 4.7,
    rooms: [],
    reviews: [],
    cheapestPrice: 300,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Rio de Janeiro Beach Hotel",
    type: "Hotel",
    country: "Brazil",
    city: "Rio de Janeiro",
    address: "789 Copacabana Avenue",
    distance: "On Copacabana Beach",
    photos: [
      "https://cf.bstatic.com/xdata/images/xphoto/1020x340/48389831.jpg?k=91f6888f904c52d6eb9ee05c1e14ddd0981c25aea2a537298ff3481ad6788233&o=",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmIOrn9G8EFA1w-PGFM-svkYFRkvJkox_XDrXXW1sCEz2Efc0ZnF8fkhYJ40O5M5vELLo&usqp=CAU",
    ],
    title: "Beachfront paradise",
    description:
      "Relax and soak up the sun at our beachfront resort on the famous Copacabana Beach in Rio de Janeiro.",
    rating: 4.6,
    rooms: [],
    reviews: [],
    cheapestPrice: 220,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Bangkok City Retreat",
    type: "Hotel",
    country: "Thailand",
    city: "Bangkok",
    address: "123 Sukhumvit Road",
    distance: "In the heart of the city",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR68_VULx6zmbJ2IP7irqOgVFcSUb5QUYMJZA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1EK1uZiIU8ZgVtf3M0XQcNd0eAXLcSc8MLWbStjxOaxf_mKL93bYGE2bREJscoQUoR2g&usqp=CAU",
    ],
    title: "Urban oasis",
    description:
      "Escape the bustling city and unwind at our tranquil retreat in the heart of Bangkok's vibrant streets.",
    rating: 4.7,
    rooms: [],
    reviews: [],
    cheapestPrice: 180,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Cairo Nile View Hotel",
    type: "Hotel",
    country: "Egypt",
    city: "Cairo",
    address: "123 Nile Street",
    distance: "Overlooking the Nile River",
    photos: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/304639151.jpg?k=7fd79e51c8f7d2b08748f88facf6632247caf5edfcabd156fe09442d066dbd90&o=&hp=1",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUceze0Y0S8mdZ7FSOSUxGgoiSw2VxltelRQ&s",
    ],
    title: "Discover ancient wonders",
    description:
      "Enjoy breathtaking views of the Nile River and explore the ancient wonders of Cairo from our riverside hotel.",
    rating: 4.8,
    rooms: [],
    reviews: [],
    cheapestPrice: 250,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Rome Historic Palace",
    type: "Resort",
    country: "Italy",
    city: "Rome",
    address: "789 Via del Colosseo",
    distance: "Next to the Colosseum",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvY64irbdJ3bRX0Z3xYKhvFeZQIoXoUJHQNg&s",
    ],
    title: "Step back in time",
    description:
      "Immerse yourself in the rich history of Rome at our historic palace resort located next to the iconic Colosseum.",
    rating: 4.8,
    reviews: [],
    cheapestPrice: 280,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Bali Beach Resort",
    type: "Resort",
    country: "Indonesia",
    city: "Bali",
    address: "123 Beachfront Avenue",
    distance: "On the pristine beach",
    photos: [
      "https://ik.imgkit.net/3vlqs5axxjf/external/http://images.ntmllc.com/v4/hotel/L46/L46115/L46115_EXT_Z8396A.JPG?tr=w-1200%2Cfo-auto",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZkr67Znp2TnY2v_BbhDSvWprq1VoLCtoOpw&s",
    ],
    title: "Tropical paradise",
    description:
      "Escape to our beachfront resort in Bali and indulge in the beauty of the island's pristine beaches and lush landscapes.",
    rating: 4.9,
    reviews: [],
    cheapestPrice: 350,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "London Riverside Resort",
    type: "Resort",
    country: "United Kingdom",
    city: "London",
    address: "456 Thames Street",
    distance: "Along the River Thames",
    photos: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/84404119.jpg?k=b7ba142df31b8579df5667c5bb479a3ef2406abecfff7b15e9b6a2d21b9fccca&o=&hp=1",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR01C5J7Qb57Oy6M9QpvSqX8rIZ54DyN3hw5X_9EOCBrslng0QG-XgT_bX6msrjZHL9wEI&usqp=CAU",
    ],
    title: "Riverside luxury",
    description:
      "Experience the charm of London from our elegant resort located along the iconic River Thames.",
    rating: 4.7,
    reviews: [],
    cheapestPrice: 300,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Rio de Janeiro Beach Resort",
    type: "Resort",
    country: "Brazil",
    city: "Rio de Janeiro",
    address: "789 Copacabana Avenue",
    distance: "On Copacabana Beach",
    photos: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/38/3f/7f/blue-tree-premium-design.jpg?w=1200&h=-1&s=1",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5Jw6LcUcuydOpwyH-bE38sWKrbpxZhdBEPzmW1a0jdHJF4F8KDjq-3V8-_il8JoQGmg4&usqp=CAU",
    ],
    title: "Beachfront paradise",
    description:
      "Relax and soak up the sun at our beachfront resort on the famous Copacabana Beach in Rio de Janeiro.",
    rating: 4.6,
    reviews: [],
    cheapestPrice: 220,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Bangkok City Retreat",
    type: "Resort",
    country: "Thailand",
    city: "Bangkok",
    address: "123 Sukhumvit Road",
    distance: "In the heart of the city",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsC8b468Go1_3vvzr3lvypFit3A7SgJTnpmQ&s",
      "https://cf.bstatic.com/xdata/images/xphoto/1020x340/48360684.jpg?k=b0007e75c61068e0df196ea633457e5ab68099e541b4b5ff6f1f38fe0b7a0723&o=",
    ],
    title: "Urban oasis",
    description:
      "Escape the bustling city and unwind at our tranquil resort in the heart of Bangkok's vibrant streets.",
    rating: 4.7,
    reviews: [],
    cheapestPrice: 180,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Cairo Nile View Resort",
    type: "Resort",
    country: "Egypt",
    city: "Cairo",
    address: "123 Nile Street",
    distance: "Overlooking the Nile River",
    photos: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/265529430.jpg?k=38bdc351298055ace6aa6b6204d19b5330dd54aa27afa59f9d1f83f1ec0a0e8c&o=&hp=1",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/265529085.jpg?k=f198370d663be3fe18714ad93bd1d54b991baa1713b6804acd6b756458a9d697&o=&hp=1",
    ],
    title: "Discover ancient wonders",
    description:
      "Enjoy breathtaking views of the Nile River and explore the ancient wonders of Cairo from our riverside resort.",
    rating: 4.8,
    reviews: [],
    cheapestPrice: 250,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Luxury Resort & Spa",
    type: "Apartment",
    country: "United States",
    city: "Miami",
    address: "123 Ocean Drive",
    distance: "2 miles from city center",
    photos: [
      "https://irp-cdn.multiscreensite.com/6dbc9417/import/base/royal-duplex-luxury-apartment-living-room-1643.jpg",
      "https://irp-cdn.multiscreensite.com/6dbc9417/import/base/apartment-presidential-suite-living-room-1139.jpg",
    ],
    title: "Experience Luxury at its Best",
    description:
      "Indulge in the opulence and comfort of our luxurious resort and spa.",
    rating: 4.8,
    reviews: [],
    cheapestPrice: 300,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Elegant Plaza Apartment",
    type: "Apartment",
    country: "France",
    city: "Paris",
    address: "456 Rue de Rivoli",
    distance: "1.5 miles from city center",
    photos: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/527347772.jpg?k=6783c7b75ba629309b31fe161befdefc1cdea73f9e0b8b2a6f43f18c083400d4&o=&hp=1",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/527346672.jpg?k=a6aa1de37b4ecdd82bc9c3a6491249b2d2a18db1126837f4ce2c88f5aa89ea3d&o=&hp=1",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/527348139.jpg?k=1a552ba2760d122dc359b18b43ef72a6446a58a2a75c75aac5314bbba7c4b159&o=&hp=1",
    ],
    title: "Charm and Comfort Combined",
    description:
      "Experience the elegance and sophistication of our centrally located hotel.",
    rating: 4.5,
    reviews: [],
    cheapestPrice: 200,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Seaside Apartments",
    type: "Apartment",
    country: "Spain",
    city: "Barcelona",
    address: "789 Beach Road",
    distance: "0.5 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-dS5uAh_YthZ9U3Za4UhWxqwc8dej3OBmIg&s",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/301942693.jpg?k=415d16685dbf032a5c67e4438c3b6edd8eea30de0b2f7a0f6c85e3be67eba5d0&o=&hp=1",
    ],
    title: "Stunning Views by the Sea",
    description:
      "Enjoy the breathtaking views from our seaside apartments in the heart of Barcelona.",
    rating: 4.6,
    reviews: [],
    cheapestPrice: 250,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Downtown Suites",
    type: "Apartment",
    country: "Canada",
    city: "Toronto",
    address: "321 Bay Street",
    distance: "1 mile from city center",
    photos: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/200570427.jpg?k=5d0e7e3453867a8c03b798cd606a9fc7193c4765f0e87924329e7f7a4e61185b&o=&hp=1",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQut7jn1I8kDLh8nNQGsvdVAhw718nIdZJF-A&s",
    ],
    title: "Modern Comfort in the Heart of Toronto",
    description:
      "Experience the urban lifestyle in our stylish downtown suites.",
    rating: 4.7,
    reviews: [],
    cheapestPrice: 280,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Alpine Chalets",
    type: "Apartment",
    country: "Switzerland",
    city: "Zurich",
    address: "10 Mountain View Road",
    distance: "3 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfXvWxu8_4VNqI7Thw62cslUkUxyMIExz1pQ&s",
      "https://alpinechaletrexburg.com/wp-content/uploads/2020/11/Alpine-Chalet2.jpg",
    ],
    title: "Ski-In, Ski-Out Luxury Chalets",
    description:
      "Unwind in our cozy alpine chalets offering direct access to the slopes.",
    rating: 4.9,
    reviews: [],
    cheapestPrice: 350,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Riverside Residences",
    type: "Apartment",
    country: "Australia",
    city: "Sydney",
    address: "555 Riverside Drive",
    distance: "1.2 miles from city center",
    photos: [
      "https://crm-cdn.ams3.cdn.digitaloceanspaces.com/c21al/storage/c21al/2023/June/week2/1024x768/721051_River_Side.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVAi8_i3oRdcYEmJg7IQ-u3x0x70BvPgvOPQ&s",
    ],
    title: "Tranquil Living by the River",
    description:
      "Experience serenity in our riverside residences offering stunning views.",
    rating: 4.6,
    reviews: [],
    cheapestPrice: 320,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Skyline Penthouse Suites",
    type: "Apartment",
    country: "United Kingdom",
    city: "London",
    address: "1 Tower Bridge",
    distance: "0.3 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxbL1KSxb3KdG6nZaELrW21pynwgjG78fmgw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf4h54B4ANexwb-UTlym_rq3RLoeLYnfF1RCAlLt-TQjAT4gqGNlOKWPBLvVNH31JeO5w&usqp=CAU",
    ],
    title: "Luxury Living with a View",
    description:
      "Enjoy breathtaking views of the London skyline from our penthouse suites.",
    rating: 4.9,
    reviews: [],
    cheapestPrice: 400,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Tropical Oasis Apartments",
    type: "Apartment",
    country: "Thailand",
    city: "Phuket",
    address: "100 Beachfront Road",
    distance: "0.1 miles from beach",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4OsZmCg4upDQbqmAbmgIi1qOFuBItOHy-gw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2fgSWKiZO3yamkU4loyDkI16UPiSLcAiTTQ&s",
    ],
    title: "Beachfront Serenity",
    description:
      "Relax in our tropical oasis apartments located on the stunning beaches of Phuket.",
    rating: 4.7,
    reviews: [],
    cheapestPrice: 600,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Metropolitan Suites",
    type: "Apartment",
    country: "Japan",
    city: "Tokyo",
    address: "789 Ginza Street",
    distance: "1.8 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0H2yDl7unfSFxTNELfRyre35hzvWBNGf-Yw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX6RdTUqX_NSukPh1Abbedf0fDz07XdJ_4TFYmFkrh58UnTveuB60Bml5iCJUK_IRfWOw&usqp=CAU",
    ],
    title: "Urban Elegance",
    description:
      "Experience modernity and comfort in the heart of Tokyo at our metropolitan suites.",
    rating: 4.6,
    reviews: [],
    cheapestPrice: 450,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Luxury Resort & Spa Villa",
    type: "Villa",
    country: "United States",
    city: "Miami",
    address: "123 Ocean Drive",
    distance: "2 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQY6tIVApX9TgU1HP_baR6U3BL9byWUUx8c3A&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwBMcOUvKbMBWjp3r7vZR8Gih22oH4l7Q7fSp0xofDCNd71-cHFbvy2RyLH4PRwewOszs&usqp=CAU",
    ],
    title: "Experience Luxury at its Best",
    description:
      "Indulge in the opulence and comfort of our luxurious resort and spa.",
    rating: 4.8,
    rooms: [],
    reviews: [],
    cheapestPrice: 300,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Elegant Plaza Villa",
    type: "Villa",
    country: "France",
    city: "Paris",
    address: "456 Rue de Rivoli",
    distance: "1.5 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhUVTcc0U2B2bHs4jsmNTWW0A1TCNIeH68vg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP9ZlmatH26vc564Q3oAOtol91jPQqlAwD1mEkh3SMZ5-a7KpBgiMi2cYUF8i-5HlETr8&usqp=CAU",
    ],
    title: "Charm and Comfort Combined",
    description:
      "Experience the elegance and sophistication of our centrally located hotel.",
    rating: 4.5,
    reviews: [],
    cheapestPrice: 200,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Seaside Apartments",
    type: "Villa",
    country: "Spain",
    city: "Barcelona",
    address: "789 Beach Road",
    distance: "0.5 miles from city center",
    photos: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/150681343.jpg?k=de04db8550c50ce24d7029738be738bcd93e819f35576f7ccc0ef5d4da2faadc&o=&hp=1",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/150681339.jpg?k=2e6637c2634f5598f72cf0c9a3bf93f6e7c6209887cd56ec51ab2377e27bf50f&o=&hp=1",
    ],
    title: "Stunning Views by the Sea",
    description:
      "Enjoy the breathtaking views from our seaside apartments in the heart of Barcelona.",
    rating: 4.6,
    reviews: [],
    cheapestPrice: 250,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Downtown Suites",
    type: "Villa",
    country: "Canada",
    city: "Toronto",
    address: "321 Bay Street",
    distance: "1 mile from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQut7jn1I8kDLh8nNQGsvdVAhw718nIdZJF-A&s",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/253922187.jpg?k=8716edd19ab3769ad5e31420bf0e6b850a1e75aeba7f0804be71bf553a649967&o=&hp=1",
    ],
    title: "Modern Comfort in the Heart of Toronto",
    description:
      "Experience the urban lifestyle in our stylish downtown suites.",
    rating: 4.7,
    reviews: [],
    cheapestPrice: 280,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Alpine Chalets",
    type: "Villa",
    country: "Switzerland",
    city: "Zurich",
    address: "10 Mountain View Road",
    distance: "3 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOZeqgHNFHLTIzTzxOfusWm5-wmseASJk6Fg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKeJnzZ3xOXZzjBnXEGoEEff6VEMNSfpJGbMqi8kbhcOhu-5ColhFogQ_oRIxAtm6Y34Q&usqp=CAU",
    ],
    title: "Ski-In, Ski-Out Luxury Chalets",
    description:
      "Unwind in our cozy alpine chalets offering direct access to the slopes.",
    rating: 4.9,
    reviews: [],
    cheapestPrice: 350,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Riverside Residences",
    type: "Villa",
    country: "Australia",
    city: "Sydney",
    address: "555 Riverside Drive",
    distance: "1.2 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWamIp8XbTF6E9ZAwugnJaZzHWr9tY2CmjpA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVNAvsgzB5Z8tIPrtItWDzR2d7tI-2Zve3Z9UzjW9BqDZPAJE9mKqzCLpq5tUIFBxWG0k&usqp=CAU",
    ],
    title: "Tranquil Living by the River",
    description:
      "Experience serenity in our riverside residences offering stunning views.",
    rating: 4.6,
    reviews: [],
    cheapestPrice: 320,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Skyline Penthouse Villas",
    type: "Villa",
    country: "United Kingdom",
    city: "London",
    address: "1 Tower Bridge",
    distance: "0.3 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRK0GMhIuYlip8FCip9_Sg-ge809GPoVUk05w&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3C_isyhYOYDMePmAxlV8I7l7q92rHbemTTgm3CyOdtXv1814lHGq5DN0Uybb82aJyNVQ&usqp=CAU",
    ],
    title: "Luxury Living with a View",
    description:
      "Enjoy breathtaking views of the London skyline from our penthouse suites.",
    rating: 4.9,
    reviews: [],
    cheapestPrice: 400,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Tropical Oasis Villas",
    type: "Villa",
    country: "Thailand",
    city: "Phuket",
    address: "100 Beachfront Road",
    distance: "0.1 miles from beach",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4CvsAU0r2u4FNhCAR6RKnWb2K64Gkqqw4_g&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwnwLo3Nj8Two9e3vm0mENUOU4UK_ZjCAbbJMs_RJwnuug-LBd4hJrBcOO9pSirarHJ3M&usqp=CAU",
    ],
    title: "Beachfront Serenity",
    description:
      "Relax in our tropical oasis villas located on the stunning beaches of Phuket.",
    rating: 4.7,
    reviews: [],
    cheapestPrice: 600,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Metropolitan Villas",
    type: "Villa",
    country: "Japan",
    city: "Tokyo",
    address: "789 Ginza Street",
    distance: "1.8 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA0S9ljk6xQLV6XhKxFULyFcPNRzjj_6JCMA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvwnOXuSF1j1_Bi8sCtKHuZJ7VYg93AqSnKNy_WaeoXoMvTNM_eTV7sdgVtgPO6dxK0qI&usqp=CAU",
    ],
    title: "Urban Elegance",
    description:
      "Experience modernity and comfort in the heart of Tokyo at our metropolitan villas.",
    rating: 4.6,
    reviews: [],
    cheapestPrice: 450,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Luxury Resort & Spa Cabin",
    type: "Cabin",
    country: "United States",
    city: "Miami",
    address: "123 Ocean Drive",
    distance: "2 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR417Rchqt2FlWgLzupDukSBa81FB8DEnX5bw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjgJ-rlThniq0V3M97WE4l20ELhayzC9ePysLTlQSDWVYUp-zeP6cVQX0zYllTLLNScFk&usqp=CAU",
    ],
    title: "Experience Luxury at its Best",
    description:
      "Indulge in the opulence and comfort of our luxurious resort and spa.",
    rating: 4.8,
    reviews: [],
    cheapestPrice: 300,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Elegant Plaza Cabin",
    type: "Cabin",
    country: "France",
    city: "Paris",
    address: "456 Rue de Rivoli",
    distance: "1.5 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBNXtwxdeIzSHB7NMjjqeYy7fvei90NddzRg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSByPteJ1nQ9CEVxdX5W2LGqNINr2WjLHruhACo8f2TlLZZ224suX9TVj2Kv2ct60-mwec&usqp=CAU",
    ],
    title: "Charm and Comfort Combined",
    description:
      "Experience the elegance and sophistication of our centrally located hotel.",
    rating: 4.5,
    reviews: [],
    cheapestPrice: 200,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Seaside Cabin",
    type: "Cabin",
    country: "Spain",
    city: "Barcelona",
    address: "789 Beach Road",
    distance: "0.5 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSB1ezPCX_h0pwiGSbiv7hHw06yz9MeM_xviQ&s",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/181597964.jpg?k=49ccc7b35171cbd6850424a845f54de272d5c600a6d0ba9ca879cbf32163e7e1&o=&hp=1",
    ],
    title: "Stunning Views by the Sea",
    description:
      "Enjoy the breathtaking views from our seaside apartments in the heart of Barcelona.",
    rating: 4.6,
    reviews: [],
    cheapestPrice: 250,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Downtown Cabins",
    type: "Cabin",
    country: "Canada",
    city: "Toronto",
    address: "321 Bay Street",
    distance: "1 mile from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuFOHEYzSelziu6cEnnqDRnHg9vrWw-8LRBOkQYzZXgHqnMCUdM2pmbmvegaKB9p7IODo&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXx0vhjP6ZOxU5Yf3y2qX3BobuD_d-KRQ9-w&s",
    ],
    title: "Modern Comfort in the Heart of Toronto",
    description:
      "Experience the urban lifestyle in our stylish downtown cabins.",
    rating: 4.7,
    reviews: [],
    cheapestPrice: 280,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Alpine Cabins",
    type: "Cabin",
    country: "Switzerland",
    city: "Zurich",
    address: "10 Mountain View Road",
    distance: "3 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQa1H-mDWkGkdmoqGUHq6LdL9PCStlqk9Rx4Q&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7rNG48rtuwgbkxNdC2FOativOWAGfC7Cs1djFXPlsxohyIyG7fSc4cetb91WD3hIf_EE&usqp=CAU",
    ],
    title: "Ski-In, Ski-Out Luxury Cabins",
    description:
      "Unwind in our cozy alpine cabins offering direct access to the slopes.",
    rating: 4.9,
    reviews: [],
    cheapestPrice: 350,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Riverside Cabins",
    type: "Cabin",
    country: "Australia",
    city: "Sydney",
    address: "555 Riverside Drive",
    distance: "1.2 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaDHS0gBxqF-X1JcNojdisGdTCRWQh9Rhh9w&sg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUICnESonT0m-uX8RYDl6-dYEkPnmbx_OWc3jIRshcsNIEWlCqgJAjq45L5mtPlc1YF7A&usqp=CAU",
    ],
    title: "Tranquil Living by the River",
    description:
      "Experience serenity in our riverside cabins offering stunning views.",
    rating: 4.6,
    reviews: [],
    cheapestPrice: 320,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Desert Oasis Cabins",
    type: "Cabin",
    country: "United Arab Emirates",
    city: "Dubai",
    address: "123 Sand Dune Road",
    distance: "20 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxiUt9_k9Bo00DyyXjPZ2ZNSChw1IZ9d-OLZVEXRsApJmiA8LO3SdciuD5FPMCoYH5ruA&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_gtgLKTiUM-jwMRzEq40HPW9t9knewVUjvg&s",
    ],
    title: "Luxury Desert Retreat",
    description: "Experience the ultimate desert getaway in our oasis cabins.",
    rating: 4.8,
    reviews: [],
    cheapestPrice: 120,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Mountain Cabins",
    type: "Cabin",
    country: "Lebanon",
    city: "Beirut",
    address: "789 Mountain Trail",
    distance: "5 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfWI7tcosUCTvqa0Ykkh-5sdp5ffdE9xWbqw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPGfOt0ToAsPWThdkYanJCKkqqCihwpSCqVEOIJLuDEBhxGDwi1XKAEClK3nt1yHJX6cs&usqp=CAU",
    ],
    title: "Scenic Mountain Retreat",
    description:
      "Escape to our mountain cabins offering stunning views and tranquility.",
    rating: 4.7,
    reviews: [],
    cheapestPrice: 400,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Red Sea Cabins",
    type: "Cabin",
    country: "Egypt",
    city: "Hurghada",
    address: "555 Red Sea Boulevard",
    distance: "0.3 miles from beach",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYJ4soj25Ds0_CWmksB6b1N1bA9qB4caaqWQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEv0ibyDmAZWC5f5AGZeOCWzwQqVhj1dtD40v4jxG7qmItsCF44fQB8EysYbMTCOF6ScE&usqp=CAU",
    ],
    title: "Seaside Cabins",
    description: "Relax in our cozy cabins by the Red Sea shore.",
    rating: 4.5,
    reviews: [],
    cheapestPrice: 250,
    featured: false,
    unavailableDates: [],
  },
  {
    HotelName: "Desert Oasis Apartments",
    type: "Apartment",
    country: "United Arab Emirates",
    city: "Dubai",
    address: "123 Sand Dune Road",
    distance: "20 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNQ1mhgRWmjIr2Kmbb8LKOcYwhVUmvBBc1LQ&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMnVyq-IPrFDB559-Mqn30YMtrsTniB3ENRw&s",
    ],
    title: "Luxury Desert Retreat",
    description:
      "Experience the ultimate desert getaway in our oasis apartments.",
    rating: 4.8,
    reviews: [],
    cheapestPrice: 120,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Mountain Apartments",
    type: "Apartment",
    country: "Lebanon",
    city: "Beirut",
    address: "789 Mountain Trail",
    distance: "5 miles from city center",
    photos: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL9mPqJbcalsFRQGtGq21MxIwaAntWXLcRNw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwz6ne3dJ6NQp0zNls4Ah-BZFxDvzaUmc5X86EFskkEUpFfzdGObBzOcfocSIuBCRxlKk&usqp=CAU",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTS56w2xRJMWd3BFYP95pDHY2YeDlUl6WMPzJrTZpCpFAGTpQ4fjUJk4KgREMdni43cjUk&usqp=CAU",
    ],
    title: "Scenic Mountain Retreat",
    description:
      "Escape to our mountain apartments offering stunning views and tranquility.",
    rating: 4.7,
    reviews: [],
    cheapestPrice: 400,
    featured: true,
    unavailableDates: [],
  },
  {
    HotelName: "Red Sea Apartments",
    type: "Apartment",
    country: "Egypt",
    city: "Hurghada",
    address: "555 Red Sea Boulevard",
    distance: "0.3 miles from beach",
    photos: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/329856120.jpg?k=ab3c18820039f6035c8d575353ea3dc6d499e7942008a49f9a6ada57a9903b53&o=&hp=1",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ32ts0pGasVSaWlVz-GqX7AnBbVpvhytYfCA4vILOPq_ic0Y4oH3H6Vhs0Vo02uELbuqw&usqp=CAU",
    ],
    title: "Seaside Apartments",
    description: "Relax in our cozy apartments by the Red Sea shore.",
    rating: 4.5,
    reviews: [],
    cheapestPrice: 250,
    featured: false,
    unavailableDates: [],
  },
];
