export const hotelsData = [
  {
    HotelName: "Luxury Resort",
    type: "Hotel",
    country: "United States",
    city: "Miami",
    address: "123 Ocean Drive",
    distance: "2 miles from downtown",
    photos: [
      "https://example.com/images/hotel1/photo1.jpg",
      "https://example.com/images/hotel1/photo2.jpg",
    ],
    title: "Experience luxury at its finest",
    description:
      "Indulge in world-class amenities and breathtaking views at our luxurious resort.",
    rating: 4.8,
    rooms: ["Deluxe Suite", "Ocean View Room", "Penthouse"], //'roomid'
    cheapestPrice: 300,
    featured: true,
  },
  {
    HotelName: "Cozy Inn",
    type: "Hotel",
    country: "France",
    city: "Paris",
    address: "456 Rue de la Paix",
    distance: "1 mile from Eiffel Tower",
    photos: [
      "https://example.com/images/hotel2/photo1.jpg",
      "https://example.com/images/hotel2/photo2.jpg",
    ],
    title: "Experience Parisian charm",
    description:
      "Enjoy a comfortable stay in the heart of Paris with our cozy rooms and warm hospitality.",
    rating: 4.2,
    rooms: ["Standard Room", "Suite"],
    cheapestPrice: 150,
    featured: false,
  },
  {
    HotelName: "Tropical Paradise Resort",
    type: "Hotel",
    country: "Thailand",
    city: "Phuket",
    address: "789 Beach Road",
    distance: "On the beachfront",
    photos: [
      "https://example.com/images/hotel3/photo1.jpg",
      "https://example.com/images/hotel3/photo2.jpg",
    ],
    title: "Escape to paradise",
    description:
      "Immerse yourself in the beauty of Phuket with our stunning beachfront resort and world-class amenities.",
    rating: 4.6,
    rooms: ["Beach Villa", "Poolside Suite", "Garden View Room"],
    cheapestPrice: 250,
    featured: true,
  },
  {
    HotelName: "City View Hotel",
    type: "Hotel",
    country: "United States",
    city: "New York",
    address: "789 Broadway",
    distance: "1 mile from Times Square",
    photos: [
      "https://example.com/images/hotel4/photo1.jpg",
      "https://example.com/images/hotel4/photo2.jpg",
    ],
    title: "Enjoy the stunning city views",
    description:
      "Stay in the heart of New York City and experience breathtaking views of the city skyline.",
    rating: 4.5,
    rooms: ["Standard Room", "Deluxe Room", "Executive Suite"],
    cheapestPrice: 200,
    featured: true,
  },
  {
    HotelName: "Mountain Retreat",
    type: "Hotel",
    country: "Switzerland",
    city: "Zermatt",
    address: "456 Alpine Street",
    distance: "In the Swiss Alps",
    photos: [
      "https://example.com/images/hotel5/photo1.jpg",
      "https://example.com/images/hotel5/photo2.jpg",
    ],
    title: "Escape to the serene mountains",
    description:
      "Experience tranquility and natural beauty in our cozy mountain retreat in Zermatt.",
    rating: 4.7,
    rooms: ["Mountain View Room", "Chalet Suite"],
    cheapestPrice: 350,
    featured: true,
  },
  {
    HotelName: "Beachfront Resort",
    type: "Hotel",
    country: "Mexico",
    city: "Cancun",
    address: "123 Beach Boulevard",
    distance: "On the beachfront",
    photos: [
      "https://example.com/images/hotel6/photo1.jpg",
      "https://example.com/images/hotel6/photo2.jpg",
    ],
    title: "Unwind in paradise",
    description:
      "Relax and rejuvenate at our beachfront resort in Cancun with pristine white sand and crystal-clear waters.",
    rating: 4.4,
    rooms: ["Ocean View Room", "Junior Suite"],
    cheapestPrice: 280,
    featured: false,
  },
  {
    HotelName: "Luxor Palace",
    type: "Hotel",
    country: "Egypt",
    city: "Luxor",
    address: "789 Nile Street",
    distance: "Near Luxor Temple",
    photos: [
      "https://example.com/images/hotel13/photo1.jpg",
      "https://example.com/images/hotel13/photo2.jpg",
    ],
    title: "Discover ancient wonders",
    description:
      "Immerse yourself in the rich history of Luxor while enjoying luxurious accommodations at our palace hotel.",
    rating: 4.7,
    rooms: ["Nile View Suite", "Deluxe Room"],
    cheapestPrice: 200,
    featured: true,
  },
  {
    HotelName: "Grand Canyon Lodge",
    type: "Hotel",
    country: "United States",
    city: "Arizona",
    address: "123 Canyon Road",
    distance: "Inside Grand Canyon National Park",
    photos: [
      "https://example.com/images/hotel14/photo1.jpg",
      "https://example.com/images/hotel14/photo2.jpg",
    ],
    title: "Experience nature's grandeur",
    description:
      "Stay in a lodge nestled within the breathtaking beauty of the Grand Canyon and enjoy stunning views.",
    rating: 4.9,
    rooms: ["Canyon View Suite", "Standard Room"],
    cheapestPrice: 250,
    featured: true,
  },
  {
    HotelName: "London Luxury Hotel",
    type: "Hotel",
    country: "United Kingdom",
    city: "London",
    address: "456 Park Lane",
    distance: "In the city center",
    photos: [
      "https://example.com/images/hotel15/photo1.jpg",
      "https://example.com/images/hotel15/photo2.jpg",
    ],
    title: "Indulge in luxury",
    description:
      "Experience the epitome of luxury and sophistication at our prestigious hotel in the heart of London.",
    rating: 4.8,
    rooms: ["Deluxe Suite", "Executive Room"],
    cheapestPrice: 350,
    featured: true,
  },
  {
    HotelName: "Barcelona Beach Resort",
    type: "Hotel",
    country: "Spain",
    city: "Barcelona",
    address: "789 Beachfront Avenue",
    distance: "On the beachfront",
    photos: [
      "https://example.com/images/hotel16/photo1.jpg",
      "https://example.com/images/hotel16/photo2.jpg",
    ],
    title: "Relax by the Mediterranean",
    description:
      "Enjoy a beachfront getaway in Barcelona with stunning views of the Mediterranean Sea.",
    rating: 4.5,
    rooms: ["Sea View Room", "Junior Suite"],
    cheapestPrice: 280,
    featured: false,
  },
  {
    HotelName: "Venice Canalside Hotel",
    type: "Hotel",
    country: "Italy",
    city: "Venice",
    address: "123 Canalside Street",
    distance: "Near St. Mark's Square",
    photos: [
      "https://example.com/images/hotel17/photo1.jpg",
      "https://example.com/images/hotel17/photo2.jpg",
    ],
    title: "Experience the charm of Venice",
    description:
      "Stay in a traditional hotel nestled along the picturesque canals of Venice and soak in the city's romantic atmosphere.",
    rating: 4.6,
    rooms: ["Canal View Suite", "Standard Room"],
    cheapestPrice: 240,
    featured: true,
  },
  {
    HotelName: "Riviera Maya Resort",
    type: "Hotel",
    country: "Mexico",
    city: "Playa del Carmen",
    address: "123 Riviera Avenue",
    distance: "On the Riviera Maya",
    photos: [
      "https://example.com/images/hotel18/photo1.jpg",
      "https://example.com/images/hotel18/photo2.jpg",
    ],
    title: "Escape to paradise",
    description:
      "Relax and unwind at our luxurious resort on the beautiful Riviera Maya with pristine beaches and turquoise waters.",
    rating: 4.7,
    rooms: ["Ocean View Suite", "Beachfront Bungalow"],
    cheapestPrice: 320,
    featured: true,
  },
  {
    HotelName: "Tokyo Tower Hotel",
    type: "Hotel",
    country: "Japan",
    city: "Tokyo",
    address: "789 Tower Street",
    distance: "Near Tokyo Tower",
    photos: [
      "https://example.com/images/hotel19/photo1.jpg",
      "https://example.com/images/hotel19/photo2.jpg",
    ],
    title: "Stay with a view",
    description:
      "Experience the vibrant city of Tokyo from the heights of our hotel near the iconic Tokyo Tower.",
    rating: 4.7,
    rooms: ["Sky View Suite", "Standard Room"],
    cheapestPrice: 180,
    featured: true,
  },
  {
    HotelName: "Sydney Harbour Hotel",
    type: "Hotel",
    country: "Australia",
    city: "Sydney",
    address: "123 Harbour Street",
    distance: "Overlooking Sydney Harbour",
    photos: [
      "https://example.com/images/hotel20/photo1.jpg",
      "https://example.com/images/hotel20/photo2.jpg",
    ],
    title: "Harbourfront luxury",
    description:
      "Enjoy stunning views of the Sydney Opera House and the Harbour Bridge from our elegant hotel.",
    rating: 4.9,
    rooms: ["Harbour View Suite", "Deluxe Room"],
    cheapestPrice: 300,
    featured: true,
  },
  {
    HotelName: "New York City Loft",
    type: "Hotel",
    country: "United States",
    city: "New York",
    address: "456 Loft Avenue",
    distance: "In the heart of Manhattan",
    photos: [
      "https://example.com/images/hotel21/photo1.jpg",
      "https://example.com/images/hotel21/photo2.jpg",
    ],
    title: "Urban chic",
    description:
      "Experience the vibrant energy of New York City from our stylish loft hotel in the heart of Manhattan.",
    rating: 4.8,
    rooms: ["Loft Suite", "Studio Room"],
    cheapestPrice: 400,
    featured: true,
  },
  {
    HotelName: "Parisian Elegance Hotel",
    type: "Hotel",
    country: "France",
    city: "Paris",
    address: "789 Champs-Élysées",
    distance: "On the famous avenue",
    photos: [
      "https://example.com/images/hotel22/photo1.jpg",
      "https://example.com/images/hotel22/photo2.jpg",
    ],
    title: "Experience Paris in style",
    description:
      "Immerse yourself in the romance and elegance of Paris at our luxurious hotel on the iconic Champs-Élysées.",
    rating: 4.7,
    rooms: ["Eiffel View Suite", "Classic Room"],
    cheapestPrice: 320,
    featured: true,
  },
  {
    HotelName: "Cape Town Beachfront Resort",
    type: "Hotel",
    country: "South Africa",
    city: "Cape Town",
    address: "123 Beach Road",
    distance: "On the beachfront",
    photos: [
      "https://example.com/images/hotel23/photo1.jpg",
      "https://example.com/images/hotel23/photo2.jpg",
    ],
    title: "Spectacular coastal retreat",
    description:
      "Escape to our beachfront resort in Cape Town and enjoy breathtaking views of the ocean and Table Mountain.",
    rating: 4.6,
    rooms: ["Ocean View Suite", "Beachfront Villa"],
    cheapestPrice: 280,
    featured: true,
  },
  {
    HotelName: "Dubai Desert Oasis",
    type: "Hotel",
    country: "United Arab Emirates",
    city: "Dubai",
    address: "123 Oasis Road",
    distance: "In the desert",
    photos: [
      "https://example.com/images/hotel24/photo1.jpg",
      "https://example.com/images/hotel24/photo2.jpg",
    ],
    title: "Luxury in the desert",
    description:
      "Experience the opulence and tranquility of our desert oasis hotel in the vibrant city of Dubai.",
    rating: 4.7,
    rooms: ["Desert View Suite", "Deluxe Room"],
    cheapestPrice: 350,
    featured: true,
  },
  {
    HotelName: "Rome Historic Palace",
    type: "Hotel",
    country: "Italy",
    city: "Rome",
    address: "789 Via del Colosseo",
    distance: "Next to the Colosseum",
    photos: [
      "https://example.com/images/hotel25/photo1.jpg",
      "https://example.com/images/hotel25/photo2.jpg",
    ],
    title: "Step back in time",
    description:
      "Immerse yourself in the rich history of Rome at our historic palace hotel located next to the iconic Colosseum.",
    rating: 4.8,
    rooms: ["Deluxe Suite", "Classic Room"],
    cheapestPrice: 280,
    featured: true,
  },
  {
    HotelName: "Bali Beach Resort",
    type: "Hotel",
    country: "Indonesia",
    city: "Bali",
    address: "123 Beachfront Avenue",
    distance: "On the pristine beach",
    photos: [
      "https://example.com/images/hotel26/photo1.jpg",
      "https://example.com/images/hotel26/photo2.jpg",
    ],
    title: "Tropical paradise",
    description:
      "Escape to our beachfront resort in Bali and indulge in the beauty of the island's pristine beaches and lush landscapes.",
    rating: 4.9,
    rooms: ["Ocean View Villa", "Garden Bungalow"],
    cheapestPrice: 350,
    featured: true,
  },
  {
    HotelName: "London Riverside Hotel",
    type: "Hotel",
    country: "United Kingdom",
    city: "London",
    address: "456 Thames Street",
    distance: "Along the River Thames",
    photos: [
      "https://example.com/images/hotel27/photo1.jpg",
      "https://example.com/images/hotel27/photo2.jpg",
    ],
    title: "Riverside luxury",
    description:
      "Experience the charm of London from our elegant hotel located along the iconic River Thames.",
    rating: 4.7,
    rooms: ["River View Suite", "Executive Room"],
    cheapestPrice: 300,
    featured: true,
  },
  {
    HotelName: "Rio de Janeiro Beach Resort",
    type: "Hotel",
    country: "Brazil",
    city: "Rio de Janeiro",
    address: "789 Copacabana Avenue",
    distance: "On Copacabana Beach",
    photos: [
      "https://example.com/images/hotel28/photo1.jpg",
      "https://example.com/images/hotel28/photo2.jpg",
    ],
    title: "Beachfront paradise",
    description:
      "Relax and soak up the sun at our beachfront resort on the famous Copacabana Beach in Rio de Janeiro.",
    rating: 4.6,
    rooms: ["Beach View Suite", "Standard Room"],
    cheapestPrice: 220,
    featured: true,
  },
  {
    HotelName: "Bangkok City Retreat",
    type: "Hotel",
    country: "Thailand",
    city: "Bangkok",
    address: "123 Sukhumvit Road",
    distance: "In the heart of the city",
    photos: [
      "https://example.com/images/hotel29/photo1.jpg",
      "https://example.com/images/hotel29/photo2.jpg",
    ],
    title: "Urban oasis",
    description:
      "Escape the bustling city and unwind at our tranquil retreat in the heart of Bangkok's vibrant streets.",
    rating: 4.7,
    rooms: ["City View Suite", "Superior Room"],
    cheapestPrice: 180,
    featured: true,
  },
  {
    HotelName: "Cairo Nile View Hotel",
    type: "Hotel",
    country: "Egypt",
    city: "Cairo",
    address: "123 Nile Street",
    distance: "Overlooking the Nile River",
    photos: [
      "https://example.com/images/hotel30/photo1.jpg",
      "https://example.com/images/hotel30/photo2.jpg",
    ],
    title: "Discover ancient wonders",
    description:
      "Enjoy breathtaking views of the Nile River and explore the ancient wonders of Cairo from our riverside hotel.",
    rating: 4.8,
    rooms: ["Nile View Suite", "Standard Room"],
    cheapestPrice: 250,
    featured: true,
  },
  {
    HotelName: "Rome Historic Palace",
    type: "Resort",
    country: "Italy",
    city: "Rome",
    address: "789 Via del Colosseo",
    distance: "Next to the Colosseum",
    photos: [
      "https://example.com/images/hotel25/photo1.jpg",
      "https://example.com/images/hotel25/photo2.jpg",
    ],
    title: "Step back in time",
    description:
      "Immerse yourself in the rich history of Rome at our historic palace resort located next to the iconic Colosseum.",
    rating: 4.8,
    rooms: ["Deluxe Suite", "Classic Room"],
    cheapestPrice: 280,
    featured: true,
  },
  {
    HotelName: "Bali Beach Resort",
    type: "Resort",
    country: "Indonesia",
    city: "Bali",
    address: "123 Beachfront Avenue",
    distance: "On the pristine beach",
    photos: [
      "https://example.com/images/hotel26/photo1.jpg",
      "https://example.com/images/hotel26/photo2.jpg",
    ],
    title: "Tropical paradise",
    description:
      "Escape to our beachfront resort in Bali and indulge in the beauty of the island's pristine beaches and lush landscapes.",
    rating: 4.9,
    rooms: ["Ocean View Villa", "Garden Bungalow"],
    cheapestPrice: 350,
    featured: true,
  },
  {
    HotelName: "London Riverside Hotel",
    type: "Resort",
    country: "United Kingdom",
    city: "London",
    address: "456 Thames Street",
    distance: "Along the River Thames",
    photos: [
      "https://example.com/images/hotel27/photo1.jpg",
      "https://example.com/images/hotel27/photo2.jpg",
    ],
    title: "Riverside luxury",
    description:
      "Experience the charm of London from our elegant resort located along the iconic River Thames.",
    rating: 4.7,
    rooms: ["River View Suite", "Executive Room"],
    cheapestPrice: 300,
    featured: true,
  },
  {
    HotelName: "Rio de Janeiro Beach Resort",
    type: "Resort",
    country: "Brazil",
    city: "Rio de Janeiro",
    address: "789 Copacabana Avenue",
    distance: "On Copacabana Beach",
    photos: [
      "https://example.com/images/hotel28/photo1.jpg",
      "https://example.com/images/hotel28/photo2.jpg",
    ],
    title: "Beachfront paradise",
    description:
      "Relax and soak up the sun at our beachfront resort on the famous Copacabana Beach in Rio de Janeiro.",
    rating: 4.6,
    rooms: ["Beach View Suite", "Standard Room"],
    cheapestPrice: 220,
    featured: true,
  },
  {
    HotelName: "Bangkok City Retreat",
    type: "Resort",
    country: "Thailand",
    city: "Bangkok",
    address: "123 Sukhumvit Road",
    distance: "In the heart of the city",
    photos: [
      "https://example.com/images/hotel29/photo1.jpg",
      "https://example.com/images/hotel29/photo2.jpg",
    ],
    title: "Urban oasis",
    description:
      "Escape the bustling city and unwind at our tranquil resort in the heart of Bangkok's vibrant streets.",
    rating: 4.7,
    rooms: ["City View Suite", "Superior Room"],
    cheapestPrice: 180,
    featured: true,
  },
  {
    HotelName: "Cairo Nile View Hotel",
    type: "Resort",
    country: "Egypt",
    city: "Cairo",
    address: "123 Nile Street",
    distance: "Overlooking the Nile River",
    photos: [
      "https://example.com/images/hotel30/photo1.jpg",
      "https://example.com/images/hotel30/photo2.jpg",
    ],
    title: "Discover ancient wonders",
    description:
      "Enjoy breathtaking views of the Nile River and explore the ancient wonders of Cairo from our riverside resort.",
    rating: 4.8,
    rooms: ["Nile View Suite", "Standard Room"],
    cheapestPrice: 250,
    featured: true,
  },
  {
    HotelName: "Luxury Resort & Spa",
    type: "Appartment",
    country: "United States",
    city: "Miami",
    address: "123 Ocean Drive",
    distance: "2 miles from city center",
    photos: [
      "https://example.com/photo1.jpg",
      "https://example.com/photo2.jpg",
    ],
    title: "Experience Luxury at its Best",
    description:
      "Indulge in the opulence and comfort of our luxurious resort and spa.",
    rating: 4.8,
    rooms: ["Deluxe Suite", "Ocean View Room", "Penthouse"],
    cheapestPrice: 300,
    featured: true,
  },
  {
    HotelName: "Elegant Plaza Hotel",
    type: "Appartment",
    country: "France",
    city: "Paris",
    address: "456 Rue de Rivoli",
    distance: "1.5 miles from city center",
    photos: [
      "https://example.com/photo3.jpg",
      "https://example.com/photo4.jpg",
    ],
    title: "Charm and Comfort Combined",
    description:
      "Experience the elegance and sophistication of our centrally located hotel.",
    rating: 4.5,
    rooms: ["Standard Room", "Executive Suite"],
    cheapestPrice: 200,
    featured: false,
  },
  {
    HotelName: "Seaside Appartments",
    type: "Appartment",
    country: "Spain",
    city: "Barcelona",
    address: "789 Beach Road",
    distance: "0.5 miles from city center",
    photos: [
      "https://example.com/photo5.jpg",
      "https://example.com/photo6.jpg",
    ],
    title: "Stunning Views by the Sea",
    description:
      "Enjoy the breathtaking views from our seaside apartments in the heart of Barcelona.",
    rating: 4.6,
    rooms: ["Oceanfront Suite", "Beachside Studio"],
    cheapestPrice: 250,
    featured: true,
  },
  {
    HotelName: "Downtown Suites",
    type: "Appartment",
    country: "Canada",
    city: "Toronto",
    address: "321 Bay Street",
    distance: "1 mile from city center",
    photos: [
      "https://example.com/photo7.jpg",
      "https://example.com/photo8.jpg",
    ],
    title: "Modern Comfort in the Heart of Toronto",
    description:
      "Experience the urban lifestyle in our stylish downtown suites.",
    rating: 4.7,
    rooms: ["City View Loft", "Executive Appartment"],
    cheapestPrice: 280,
    featured: true,
  },
  {
    HotelName: "Alpine Chalets",
    type: "Appartment",
    country: "Switzerland",
    city: "Zurich",
    address: "10 Mountain View Road",
    distance: "3 miles from city center",
    photos: [
      "https://example.com/photo9.jpg",
      "https://example.com/photo10.jpg",
    ],
    title: "Ski-In, Ski-Out Luxury Chalets",
    description:
      "Unwind in our cozy alpine chalets offering direct access to the slopes.",
    rating: 4.9,
    rooms: ["Ski Chalet", "Mountain View Appartment"],
    cheapestPrice: 350,
    featured: true,
  },
  {
    HotelName: "Riverside Residences",
    type: "Appartment",
    country: "Australia",
    city: "Sydney",
    address: "555 Riverside Drive",
    distance: "1.2 miles from city center",
    photos: [
      "https://example.com/photo11.jpg",
      "https://example.com/photo12.jpg",
    ],
    title: "Tranquil Living by the River",
    description:
      "Experience serenity in our riverside residences offering stunning views.",
    rating: 4.6,
    rooms: ["River View Suite", "Nature Retreat"],
    cheapestPrice: 320,
    featured: false,
  },
  {
    HotelName: "Skyline Penthouse Suites",
    type: "Appartment",
    country: "United Kingdom",
    city: "London",
    address: "1 Tower Bridge",
    distance: "0.3 miles from city center",
    photos: [
      "https://example.com/photo13.jpg",
      "https://example.com/photo14.jpg",
    ],
    title: "Luxury Living with a View",
    description:
      "Enjoy breathtaking views of the London skyline from our penthouse suites.",
    rating: 4.9,
    rooms: ["Executive Penthouse", "Sky View Appartment"],
    cheapestPrice: 400,
    featured: true,
  },
  {
    HotelName: "Tropical Oasis Appartments",
    type: "Appartment",
    country: "Thailand",
    city: "Phuket",
    address: "100 Beachfront Road",
    distance: "0.1 miles from beach",
    photos: [
      "https://example.com/photo15.jpg",
      "https://example.com/photo16.jpg",
    ],
    title: "Beachfront Serenity",
    description:
      "Relax in our tropical oasis apartments located on the stunning beaches of Phuket.",
    rating: 4.7,
    rooms: ["Beach View Appartment", "Tropical Retreat"],
    cheapestPrice: 600,
    featured: true,
  },
  {
    HotelName: "Metropolitan Suites",
    type: "Appartment",
    country: "Japan",
    city: "Tokyo",
    address: "789 Ginza Street",
    distance: "1.8 miles from city center",
    photos: [
      "https://example.com/photo17.jpg",
      "https://example.com/photo18.jpg",
    ],
    title: "Urban Elegance",
    description:
      "Experience modernity and comfort in the heart of Tokyo at our metropolitan suites.",
    rating: 4.6,
    rooms: ["Cityscape View Room", "Executive Studio"],
    cheapestPrice: 450,
    featured: false,
  },
  {
    HotelName: "Luxury Resort & Spa",
    type: "Villa",
    country: "United States",
    city: "Miami",
    address: "123 Ocean Drive",
    distance: "2 miles from city center",
    photos: [
      "https://example.com/photo1.jpg",
      "https://example.com/photo2.jpg",
    ],
    title: "Experience Luxury at its Best",
    description:
      "Indulge in the opulence and comfort of our luxurious resort and spa.",
    rating: 4.8,
    rooms: ["Deluxe Suite", "Ocean View Room", "Penthouse"],
    cheapestPrice: 300,
    featured: true,
  },
  {
    HotelName: "Elegant Plaza Hotel",
    type: "Villa",
    country: "France",
    city: "Paris",
    address: "456 Rue de Rivoli",
    distance: "1.5 miles from city center",
    photos: [
      "https://example.com/photo3.jpg",
      "https://example.com/photo4.jpg",
    ],
    title: "Charm and Comfort Combined",
    description:
      "Experience the elegance and sophistication of our centrally located hotel.",
    rating: 4.5,
    rooms: ["Standard Room", "Executive Suite"],
    cheapestPrice: 200,
    featured: false,
  },
  {
    HotelName: "Seaside Appartments",
    type: "Villa",
    country: "Spain",
    city: "Barcelona",
    address: "789 Beach Road",
    distance: "0.5 miles from city center",
    photos: [
      "https://example.com/photo5.jpg",
      "https://example.com/photo6.jpg",
    ],
    title: "Stunning Views by the Sea",
    description:
      "Enjoy the breathtaking views from our seaside apartments in the heart of Barcelona.",
    rating: 4.6,
    rooms: ["Oceanfront Suite", "Beachside Studio"],
    cheapestPrice: 250,
    featured: true,
  },
  {
    HotelName: "Downtown Suites",
    type: "Villa",
    country: "Canada",
    city: "Toronto",
    address: "321 Bay Street",
    distance: "1 mile from city center",
    photos: [
      "https://example.com/photo7.jpg",
      "https://example.com/photo8.jpg",
    ],
    title: "Modern Comfort in the Heart of Toronto",
    description:
      "Experience the urban lifestyle in our stylish downtown suites.",
    rating: 4.7,
    rooms: ["City View Loft", "Executive Appartment"],
    cheapestPrice: 280,
    featured: true,
  },
  {
    HotelName: "Alpine Chalets",
    type: "Villa",
    country: "Switzerland",
    city: "Zurich",
    address: "10 Mountain View Road",
    distance: "3 miles from city center",
    photos: [
      "https://example.com/photo9.jpg",
      "https://example.com/photo10.jpg",
    ],
    title: "Ski-In, Ski-Out Luxury Chalets",
    description:
      "Unwind in our cozy alpine chalets offering direct access to the slopes.",
    rating: 4.9,
    rooms: ["Ski Chalet", "Mountain View Appartment"],
    cheapestPrice: 350,
    featured: true,
  },
  {
    HotelName: "Riverside Residences",
    type: "Villa",
    country: "Australia",
    city: "Sydney",
    address: "555 Riverside Drive",
    distance: "1.2 miles from city center",
    photos: [
      "https://example.com/photo11.jpg",
      "https://example.com/photo12.jpg",
    ],
    title: "Tranquil Living by the River",
    description:
      "Experience serenity in our riverside residences offering stunning views.",
    rating: 4.6,
    rooms: ["River View Suite", "Nature Retreat"],
    cheapestPrice: 320,
    featured: false,
  },
  {
    HotelName: "Skyline Penthouse Suites",
    type: "Villa",
    country: "United Kingdom",
    city: "London",
    address: "1 Tower Bridge",
    distance: "0.3 miles from city center",
    photos: [
      "https://example.com/photo13.jpg",
      "https://example.com/photo14.jpg",
    ],
    title: "Luxury Living with a View",
    description:
      "Enjoy breathtaking views of the London skyline from our penthouse suites.",
    rating: 4.9,
    rooms: ["Executive Penthouse", "Sky View Appartment"],
    cheapestPrice: 400,
    featured: true,
  },
  {
    HotelName: "Tropical Oasis Villas",
    type: "Villa",
    country: "Thailand",
    city: "Phuket",
    address: "100 Beachfront Road",
    distance: "0.1 miles from beach",
    photos: [
      "https://example.com/photo15.jpg",
      "https://example.com/photo16.jpg",
    ],
    title: "Beachfront Serenity",
    description:
      "Relax in our tropical oasis villas located on the stunning beaches of Phuket.",
    rating: 4.7,
    rooms: ["Beach View Villa", "Tropical Retreat"],
    cheapestPrice: 600,
    featured: true,
  },
  {
    HotelName: "Metropolitan Villas",
    type: "Villa",
    country: "Japan",
    city: "Tokyo",
    address: "789 Ginza Street",
    distance: "1.8 miles from city center",
    photos: [
      "https://example.com/photo17.jpg",
      "https://example.com/photo18.jpg",
    ],
    title: "Urban Elegance",
    description:
      "Experience modernity and comfort in the heart of Tokyo at our metropolitan villas.",
    rating: 4.6,
    rooms: ["Cityscape View Villa", "Executive Studio"],
    cheapestPrice: 450,
    featured: false,
  },
  {
    HotelName: "Luxury Resort & Spa",
    type: "Cabin",
    country: "United States",
    city: "Miami",
    address: "123 Ocean Drive",
    distance: "2 miles from city center",
    photos: [
      "https://example.com/photo1.jpg",
      "https://example.com/photo2.jpg",
    ],
    title: "Experience Luxury at its Best",
    description:
      "Indulge in the opulence and comfort of our luxurious resort and spa.",
    rating: 4.8,
    rooms: ["Deluxe Suite", "Ocean View Room", "Penthouse"],
    cheapestPrice: 300,
    featured: true,
  },
  {
    HotelName: "Elegant Plaza Hotel",
    type: "Cabin",
    country: "France",
    city: "Paris",
    address: "456 Rue de Rivoli",
    distance: "1.5 miles from city center",
    photos: [
      "https://example.com/photo3.jpg",
      "https://example.com/photo4.jpg",
    ],
    title: "Charm and Comfort Combined",
    description:
      "Experience the elegance and sophistication of our centrally located hotel.",
    rating: 4.5,
    rooms: ["Standard Room", "Executive Suite"],
    cheapestPrice: 200,
    featured: false,
  },
  {
    HotelName: "Seaside Appartments",
    type: "Cabin",
    country: "Spain",
    city: "Barcelona",
    address: "789 Beach Road",
    distance: "0.5 miles from city center",
    photos: [
      "https://example.com/photo5.jpg",
      "https://example.com/photo6.jpg",
    ],
    title: "Stunning Views by the Sea",
    description:
      "Enjoy the breathtaking views from our seaside apartments in the heart of Barcelona.",
    rating: 4.6,
    rooms: ["Oceanfront Suite", "Beachside Studio"],
    cheapestPrice: 250,
    featured: true,
  },
  {
    HotelName: "Downtown Cabins",
    type: "Cabin",
    country: "Canada",
    city: "Toronto",
    address: "321 Bay Street",
    distance: "1 mile from city center",
    photos: [
      "https://example.com/photo7.jpg",
      "https://example.com/photo8.jpg",
    ],
    title: "Modern Comfort in the Heart of Toronto",
    description:
      "Experience the urban lifestyle in our stylish downtown cabins.",
    rating: 4.7,
    rooms: ["City View Cabin", "Executive Cabin"],
    cheapestPrice: 280,
    featured: true,
  },
  {
    HotelName: "Alpine Cabins",
    type: "Cabin",
    country: "Switzerland",
    city: "Zurich",
    address: "10 Mountain View Road",
    distance: "3 miles from city center",
    photos: [
      "https://example.com/photo9.jpg",
      "https://example.com/photo10.jpg",
    ],
    title: "Ski-In, Ski-Out Luxury Cabins",
    description:
      "Unwind in our cozy alpine cabins offering direct access to the slopes.",
    rating: 4.9,
    rooms: ["Ski Cabin", "Mountain View Cabin"],
    cheapestPrice: 350,
    featured: true,
  },
  {
    HotelName: "Riverside Cabins",
    type: "Cabin",
    country: "Australia",
    city: "Sydney",
    address: "555 Riverside Drive",
    distance: "1.2 miles from city center",
    photos: [
      "https://example.com/photo11.jpg",
      "https://example.com/photo12.jpg",
    ],
    title: "Tranquil Living by the River",
    description:
      "Experience serenity in our riverside cabins offering stunning views.",
    rating: 4.6,
    rooms: ["River View Cabin", "Nature Retreat"],
    cheapestPrice: 320,
    featured: false,
  },
  {
    HotelName: "Desert Oasis Cabins",
    type: "Cabin",
    country: "United Arab Emirates",
    city: "Dubai",
    address: "123 Sand Dune Road",
    distance: "20 miles from city center",
    photos: [
      "https://example.com/photo19.jpg",
      "https://example.com/photo20.jpg",
    ],
    title: "Luxury Desert Retreat",
    description: "Experience the ultimate desert getaway in our oasis cabins.",
    rating: 4.8,
    rooms: ["Safari Cabin", "Dune View Cabin"],
    cheapestPrice: 120,
    featured: true,
  },
  {
    HotelName: "Mountain Cabins",
    type: "Cabin",
    country: "Lebanon",
    city: "Beirut",
    address: "789 Mountain Trail",
    distance: "5 miles from city center",
    photos: [
      "https://example.com/photo21.jpg",
      "https://example.com/photo22.jpg",
    ],
    title: "Scenic Mountain Retreat",
    description:
      "Escape to our mountain cabins offering stunning views and tranquility.",
    rating: 4.7,
    rooms: ["Valley View Cabin", "Forest Retreat Cabin"],
    cheapestPrice: 400,
    featured: true,
  },
  {
    HotelName: "Red Sea Cabins",
    type: "Cabin",
    country: "Egypt",
    city: "Hurghada",
    address: "555 Red Sea Boulevard",
    distance: "0.3 miles from beach",
    photos: [
      "https://example.com/photo23.jpg",
      "https://example.com/photo24.jpg",
    ],
    title: "Seaside Cabins",
    description: "Relax in our cozy cabins by the Red Sea shore.",
    rating: 4.5,
    rooms: ["Seaview Cabin", "Beachfront Cabin"],
    cheapestPrice: 250,
    featured: false,
  },
  {
    HotelName: "Desert Oasis Appartments",
    type: "Appartment",
    country: "United Arab Emirates",
    city: "Dubai",
    address: "123 Sand Dune Road",
    distance: "20 miles from city center",
    photos: [
      "https://example.com/photo19.jpg",
      "https://example.com/photo20.jpg",
    ],
    title: "Luxury Desert Retreat",
    description:
      "Experience the ultimate desert getaway in our oasis apartments.",
    rating: 4.8,
    rooms: ["Safari Appartment", "Dune View Appartment"],
    cheapestPrice: 120,
    featured: true,
  },
  {
    HotelName: "Mountain Appartments",
    type: "Appartment",
    country: "Lebanon",
    city: "Beirut",
    address: "789 Mountain Trail",
    distance: "5 miles from city center",
    photos: [
      "https://example.com/photo21.jpg",
      "https://example.com/photo22.jpg",
    ],
    title: "Scenic Mountain Retreat",
    description:
      "Escape to our mountain apartments offering stunning views and tranquility.",
    rating: 4.7,
    rooms: ["Valley View Appartment", "Forest Retreat Appartment"],
    cheapestPrice: 400,
    featured: true,
  },
  {
    HotelName: "Red Sea Appartments",
    type: "Appartment",
    country: "Egypt",
    city: "Hurghada",
    address: "555 Red Sea Boulevard",
    distance: "0.3 miles from beach",
    photos: [
      "https://example.com/photo23.jpg",
      "https://example.com/photo24.jpg",
    ],
    title: "Seaside Appartments",
    description: "Relax in our cozy apartments by the Red Sea shore.",
    rating: 4.5,
    rooms: ["Seaview Appartment", "Beachfront Appartment"],
    cheapestPrice: 250,
    featured: false,
  },
];
